### ISSUE TITLE
[Example] Missing conf['class'] when running flask example

### ISSUE THREAD

**Issue by peppelinux** [rohe/oidc-op#2]
Hi, I'm playing with oidc-op and flask.
I'm also working on a basic Readme to help users with preliminar setup.

Running  `python -m flask_op.server flask_op/conf.yaml ` I get the following exception.
Am I doing something wrong?

````
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/DEV3/oidc-op/flask_op/server.py", line 34, in <module>
    main(args.config)
  File "~/DEV3/oidc-op/flask_op/server.py", line 18, in main
    app = oidc_provider_init_app(config, 'oidc_op')
  File "~/DEV3/oidc-op/flask_op/application.py", line 56, in oidc_provider_init_app
    app.endpoint_context = init_oidc_op_endpoints(app)
  File "~/DEV3/oidc-op/flask_op/application.py", line 30, in init_oidc_op_endpoints
    cwd=folder)
  File "~/DEV3/Django-Identity.env/lib/python3.5/site-packages/oidcendpoint/endpoint_context.py", line 190, in __init__
    self.cookie_dealer = init_service(_conf)
  File "~/DEV3/Django-Identity.env/lib/python3.5/site-packages/oidcendpoint/endpoint_context.py", line 102, in init_service
    if isinstance(conf['class'], str):
KeyError: 'class'
````

**Comment by peppelinux** [comment]
Fixed with latests commits, thank you
